# config.yaml
database: "testdb.duckdb"
tables:
  - pattern: "TBL01_*.csv"
    table: "TBL01"
    skip_rows: [1]  # 1行目だけスキップ
  - pattern: "TEST_*.csv"
    table: "TEST"
    skip_rows: [1, 2]  # 1行目と2行目をスキップ
